service: serverless-chrome

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  environment:
    CHROME_PATH: ./headless-chrome/headless_shell

custom:
  webpackIncludeModules: false # disable auto including modules

plugins:
  - serverless-webpack

functions:
  run:
    description: Run headless Chromium
    memorySize: 512
    timeout: 30
    handler: handler.run

    events:
      - http:
          path: /pdfexport
          method: post
          integration: lambda-proxy
